steps:
  - name: Hello world action
    with: # Set the secret as an input
      super_secret: ${{ secrets.AI_URL }}
    env: # Or as an environment variable
      super_secret: ${{ secrets.AI_URL }}