name: Workflows with a secret

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        with: # Set the secret as an input
          super_secret: ${{ secrets.AI_URL }}
        env: # Or as an environment variable
          super_secret: ${{ secrets.AI_URL }}