name: workflow with a secret

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env: # Or as an environment variable
          SUPER_SECRET: ${{ secrets.AI_URL }}
        run: |
          example-command "$SUPER_SECRET"
