name: workflow with a secret

on: [push]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setting secret .env
        run: | 
          echo "AI_URL = $AI_URL" >> .env
        env:
          AI_URL: ${{secrets.AI_URL}}